name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf # v2.2.0
        with:
          platform: x86

      - name: Build
        run: |
          i686-w64-mingw32-g++-win32 -static-libgcc -static-libstdc++ -shared \
          -I "states_dll/include" \
          -I "states_dll/stdfunc/include" \
          -I "states_dll/include/mingw-std-threads" \
          -I "states_dll/Detours/src" \
          states_dll/src/* \
          states_dll/stdfunc/src/* \
          -o states.dll
